export const LABELS = [
  "PRAISE_EXPERIENCE",
  "REQUEST_PRODUCT",
  "REQUEST_ACTIVITY",
  "PURCHASE_INTENT",
  "BOOKING_INTENT",
  "RETURN_REFERRAL_INTENT",
  "FRICTION_ACCESS",
  "FRICTION_PRICE",
  "FRICTION_EXPERIENCE",
  "COMMUNICATION_GAP",
  "PAYMENT_FRICTION",
  "ACCESSIBILITY_REQUIREMENT",
  "DIETARY_PREFERENCE",
  "SAFETY_REQUIREMENT",
  "CULTURAL_SENSITIVITY",
  "OTHER",
  "UNKNOWN",
] as const;

export type SignalLabel = (typeof LABELS)[number];

export const HUMAN_CONFIRM_REQUIRED = new Set<SignalLabel>([
  "SAFETY_REQUIREMENT",
  "ACCESSIBILITY_REQUIREMENT",
]);
